import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        

      </head>
      <body>
        <header>
          
          <nav>
            <ul>
              <h2 className="font-geist-sans font-bold text-2xl ">Baldi&apos;s Leader</h2>
              <li><Link href={"/"}>Home</Link></li>
              <li><Link href={"/blogs"}>Blogs</Link></li>
              <li><Link href={"/chat"}>Chat</Link></li>
              <li><Link href={"/links"}>My Links</Link></li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>

      </body>
    </html>
  );
}
